# We did it boys, makefile is no more

#jk, moved to build
# this is bs but it works 

all: 
	make -C ./build/

clean: 
	make -C ./build/ clean

send: 
	scp -P4257 ./bin/ssl-Client organizador@131.221.240.153:~/yapira